allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@types/node@26.1.2 || 26.2.0'
  - '@rolldown/binding-win32-x64-msvc@1.2.1 || 1.2.2 || 1.2.3'
  - tsx@4.23.4 || 4.23.5 || 4.23.6 || 4.23.8 || 4.23.9 || 4.23.11 || 4.23.12
  - '@typescript-eslint/eslint-plugin@8.66.0'
  - '@typescript-eslint/parser@8.66.0'
  - '@typescript-eslint/project-service@8.66.0'
  - '@typescript-eslint/scope-manager@8.66.0'
  - '@typescript-eslint/tsconfig-utils@8.66.0'
  - '@typescript-eslint/type-utils@8.66.0'
  - '@typescript-eslint/types@8.66.0'
  - '@typescript-eslint/typescript-estree@8.66.0'
  - '@typescript-eslint/utils@8.66.0'
  - '@typescript-eslint/visitor-keys@8.66.0'
  - typescript-eslint@8.66.0
  - eslint@10.8.1
